# Generated by Django 4.2.11 on 2024-05-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_message_receiver_message_sender_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
